name = "Bluehaven Borough"
author = "Dani"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[versions]
minecraft = "1.20.1"
forge = "47.2.20"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42da4a66beeb5013055dfcdd2a0887b4ec842b1a6b168c690aba784c27f2d8fd"
